Pre-commit hook now will prettify Go Code

diff --git a/hooks/common/pre-commit b/hooks/common/pre-commit
--- a/hooks/common/pre-commit
+++ b/hooks/common/pre-commit
@@ -26,17 +26,28 @@ if ! get_config_bool gitflow.allow-conflict-commit; then
   [[ ${#files_to_merge[@]} > 0 ]] && die "Resolve these merges before committing! ${files_to_merge[@]}"
 fi
 
-STAGED_GO_FILES=$(git diff --cached --name-only | grep "\.go$")
-[[ -z $STAGED_GO_FILES ]] && exit 0
+STAGED_GO_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep "\.go$")
 
-GOFMT=$(command -v gofmt)
-if (( $? )); then
-  GOFMT=$GOROOT/bin/gofmt
-  [[ ! -e $GOFMT ]] && die "The gofmt tool is missing, aborting"
+if get_config_bool gitflow.prettify true; then
+  GOFMT=$(command -v gofmt)
+  if (( $? )); then
+    GOFMT=$GOROOT/bin/gofmt
+    [[ ! -e $GOFMT ]] && die "The gofmt tool is missing, aborting"
+  fi
+
+  stop_processing=0
+  for file in $STAGED_GO_FILES ; do
+    output=$($GOFMT -s -w $file)
+    # Any output from gofmt indicates a problem
+    if [[ -n $output ]]; then
+      error "$file is not formatted properly: $output"
+      stop_processing=1
+    else
+      git add $file
+    fi
+  done
+  (( stop_processing )) && die "Fix the formatting errors and try again"
 fi
 
-for file in $STAGED_GO_FILES ; do
-  $GOFMT -w $file
-done
 
 exit 0
